Tests_task:
  # Run tests on macOS Mojave:
  osx_instance:
    image: mojave-xcode-10.1
  # Don't run on Python2 branch:
  only_if: $CIRRUS_BRANCH != 'python-2-supported'
  # Do not skip if new commits are pushed to master:
  auto_cancellation: $CIRRUS_BRANCH != 'master'

  # Install Python3 and NodeJS:
  Install_Python_script:
    - brew install python@3
  Install_NodeJS_script:
    - brew install node

  # Clean workspace:
  Clean_Workspace_script:
    - make clean

  # Install test dependencies:
  Install_Test_Dependencies_script:
    - make testrequirements
    - make devrequirements
    - make installlinkcheck
    - make installmdlint

  # Build the package:
  Build_Package_script:
    - make dist

  # Install new beta build:
  Install_Beta_Build_script:
    - make beta

  # Test the Python code:
  Run_Python_Tests_script:
    - make test

  # Run Python linting:
  PythonLinting_script:
    - make pydocstyle
    - make pycodestyle
    - make flake8
    - make pylint

  # Test dependencies for security issues:
  Dependency_Security_Test_script:
    - make safetyci

  # Lint Markdown:
  Markdown_Tests_script:
    - find . -name '*.md' -exec markdownlint --config=.markdownlint.yml {} \;
    - make linkcheck
