container:
  image: python:latest

Build_task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat requirements.txt
    populate_script: python3 -m pip install --upgrade setuptools wheel twine
  Build_script: python3 setup.py sdist bdist_wheel

MarkdownTests_task:
  container:
    image: node:latest
  InstallLinter_script: npm install -g markdownlint-cli
  InstallLinkChecker_script: npm install -g markdown-link-check@3.7.2
  Lint_script:
    - markdownlint --config=.markdownlint.yml *.md
    - markdownlint --config=.markdownlint.yml .github/*.md
  LinkCheck_script: find . -name \*.md -exec markdown-link-check {} \;
