Tests_task:
  # Run tests on macOS Mojave:
  osx_instance:
    image: mojave-xcode-10.1

  # Don't run on Python2 branch:
  only_if: $CIRRUS_BRANCH != 'python-2-supported'

  # Do not skip if new commits are pushed to master:
  auto_cancellation: $CIRRUS_REPO == 'RDIL/area4'

  # Install Python3 and NodeJS:
  Install_Python_script:
    - brew install python@3
  Install_NodeJS_script:
    - brew install node

  # Install test dependencies:
  Install_Test_Dependencies_script:
    - python3 -m pip install -r $CIRRUS_WORKING_DIR/requirements/test.txt
    - python3 -m pip install -r $CIRRUS_WORKING_DIR/requirements/dev.txt
    - npm install markdown-link-check@3.7.2
    - npm install markdownlint-cli

  # Install new beta build:
  Install_Beta_Build_script:
    - make beta

  # Test the Python code:
  Run_Python_Tests_script:
    - make test
    - make safetyci

  # Run Python linting:
  Python_Linting_script:
    - make pydocstyle
    - make pycodestyle
    - make flake8
    - make pylint

  # Lint Markdown:
  Markdown_Tests_script:
    - find . -name '*.md' -exec markdownlint --config=.markdownlint.yml {} \;
    - make linkcheck
