test_task:
  container:
    image: python:latest
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat requirements.txt
    populate_script: python3 -m pip install --upgrade setuptools wheel twine
  test_script: python3 setup.py sdist bdist_wheel

markdown_tests_task:
  container:
    image: node:latest
  install_linter_script: npm install -g markdownlint-cli
  install_link_checker_script: npm install -g markdown-link-check@3.7.2
  lint_script: markdownlint --config=.markdownlint.yml *.md
  link_check_script: find . -name \*.md -exec markdown-link-check {} \;
